[build-system]
requires = [
    "scikit-build-core",
    "mpi4py",
    "pybind11"
]
build-backend = "scikit_build_core.build"

[project]
dependencies = ["mpi4py>=3.1", "numpy>=1.21"]
description = "Generic Halo Exchanges: Python API"
name = "ghex"
license = {file = "../../LICENSE"}
readme = {file = "../../README.md", content-type = "text/markdown"}
version = "0.3.0"

[project.urls]
repository = "https://github.com/ghex-org/GHEX"

[project.optional-dependencies]
test = ["pytest"]

[tool.scikit-build]
cmake.minimum-version = "3.17"
cmake.source-dir = "../.."
cmake.build-type = "Release"
cmake.args = [
    "-DGHEX_BUILD_PYTHON_BINDINGS=ON",
    "-DGHEX_USE_BUNDLED_LIBS=ON",
    "-DGHEX_USE_BUNDLED_GRIDTOOLS=ON",
    "-DGHEX_USE_BUNDLED_OOMPH=ON",
]
wheel.expand-macos-universal-tags = true
wheel.install-dir = "ghex"
wheel.packages = []
wheel.license-files = []
