name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu-mpi:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DOOMPH_WITH_MPI=ON \
            -DGHEX_TRANSPORT_BACKEND=MPI \
            -DHWMALLOC_ENABLE_DEVICE=OFF \
            -DGHEX_USE_GPU=OFF \
            -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
            -DGHEX_BUILD_FORTRAN=ON \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DMPIEXEC_PREFLAGS=--oversubscribe
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-cpu-ucx:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DOOMPH_WITH_UCX=ON \
              -DGHEX_TRANSPORT_BACKEND=UCX \
              -DHWMALLOC_ENABLE_DEVICE=OFF \
              -DGHEX_USE_GPU=OFF \
              -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
              -DGHEX_BUILD_FORTRAN=ON \
              -DGHEX_WITH_TESTING=ON \
              -DGHEX_BUILD_BENCHMARKS=ON \
              -DMPIEXEC_PREFLAGS=--oversubscribe \
              -DUCX_DIR=/opt/ucx 
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-cpu-mpi-clang:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-hip

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          CXX=/opt/rocm/llvm/bin/clang++ eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DOOMPH_WITH_MPI=ON \
              -DGHEX_TRANSPORT_BACKEND=MPI \
              -DHWMALLOC_ENABLE_DEVICE=OFF \
              -DGHEX_USE_GPU=OFF \
              -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
              -DGHEX_BUILD_FORTRAN=ON \
              -DGHEX_WITH_TESTING=ON \
              -DGHEX_BUILD_BENCHMARKS=ON \
              -DMPIEXEC_PREFLAGS=--oversubscribe
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-cpu-ucx_clang:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-hip

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          CXX=/opt/rocm/llvm/bin/clang++ eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DOOMPH_WITH_UCX=ON \
              -DGHEX_TRANSPORT_BACKEND=UCX \
              -DHWMALLOC_ENABLE_DEVICE=OFF \
              -DGHEX_USE_GPU=OFF \
              -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
              -DGHEX_BUILD_FORTRAN=ON \
              -DGHEX_WITH_TESTING=ON \
              -DGHEX_BUILD_BENCHMARKS=ON \
              -DMPIEXEC_PREFLAGS=--oversubscribe \
              -DUCX_DIR=/opt/ucx 
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-gpu-amd:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-hip

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          CXX=/opt/rocm/llvm/bin/clang++ cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DOOMPH_WITH_UCX=ON \
              -DGHEX_TRANSPORT_BACKEND=UCX \
              -DUCX_DIR=/opt/ucx \
              -DHWMALLOC_ENABLE_DEVICE=ON \
              -DGHEX_USE_GPU=ON \
              -DHWMALLOC_DEVICE_RUNTIME=hip \
              -DGHEX_GPU_TYPE=AMD \
              -DGHEX_WITH_TESTING=ON \
              -DGHEX_BUILD_BENCHMARKS=ON \
              -DMPIEXEC_PREFLAGS=--oversubscribe \
              -DGHEX_ENABLE_ATLAS_BINDINGS=OFF \
              -DGHEX_BUILD_FORTRAN=ON
      - name: Build
        run: cmake --build build --parallel 2

  build-gpu-nvidia:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-cuda-11

    steps:
      - uses: actions/checkout@v1
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DOOMPH_WITH_UCX=ON \
              -DGHEX_TRANSPORT_BACKEND=UCX \
              -DUCX_DIR=/opt/ucx \
              -DHWMALLOC_ENABLE_DEVICE=ON \
              -DGHEX_USE_GPU=ON \
              -DHWMALLOC_DEVICE_RUNTIME=cuda \
              -DGHEX_GPU_TYPE=NVIDIA \
              -DGHEX_WITH_TESTING=ON \
              -DGHEX_BUILD_BENCHMARKS=ON \
              -DMPIEXEC_PREFLAGS=--oversubscribe \
              -DGHEX_ENABLE_ATLAS_BINDINGS=OFF \
              -DGHEX_BUILD_FORTRAN=ON
      - name: Build
        run: cmake --build build --parallel 2
