name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu-mpi:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGHEX_GIT_SUBMODULE=OFF \
            -DGHEX_USE_BUNDLED_LIBS=ON \
            -DGHEX_USE_BUNDLED_GRIDTOOLS=ON \
            -DBUILD_TESTING=OFF \
            -DGT_BUILD_TESTING=OFF \
            -DGT_INSTALL_EXAMPLES=OFF \
            -DGHEX_TRANSPORT_BACKEND=MPI \
            -DGHEX_USE_BUNDLED_OOMPH=ON \
            -DGHEX_USE_XPMEM=OFF \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DGHEX_BUILD_FORTRAN=ON \
            -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
            -DGHEX_ENABLE_PARMETIS_BINDINGS=ON \
            -DMETIS_INCLUDE_DIR=/opt/metis/include \
            -DMETIS_LIB_DIR=/opt/metis/lib \
            -DPARMETIS_INCLUDE_DIR=/opt/parmetis/include \
            -DPARMETIS_LIB_DIR=/opt/parmetis/lib \
            -DMPIEXEC_PREFLAGS=--oversubscribe \
            -DGHEX_USE_GPU=OFF
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-cpu-ucx:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGHEX_GIT_SUBMODULE=OFF \
            -DGHEX_USE_BUNDLED_LIBS=ON \
            -DGHEX_USE_BUNDLED_GRIDTOOLS=ON \
            -DBUILD_TESTING=OFF \
            -DGT_BUILD_TESTING=OFF \
            -DGT_INSTALL_EXAMPLES=OFF \
            -DGHEX_USE_BUNDLED_OOMPH=ON \
            -DGHEX_TRANSPORT_BACKEND=UCX \
            -DUCX_DIR=/opt/ucx \
            -DGHEX_USE_XPMEM=OFF \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DGHEX_BUILD_FORTRAN=ON \
            -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
            -DGHEX_ENABLE_PARMETIS_BINDINGS=ON \
            -DMETIS_INCLUDE_DIR=/opt/metis/include \
            -DMETIS_LIB_DIR=/opt/metis/lib \
            -DPARMETIS_INCLUDE_DIR=/opt/parmetis/include \
            -DPARMETIS_LIB_DIR=/opt/parmetis/lib \
            -DMPIEXEC_PREFLAGS=--oversubscribe \
            -DGHEX_USE_GPU=OFF
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-cpu-mpi-clang:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-hip
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          CXX=/opt/rocm/llvm/bin/clang++ eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGHEX_GIT_SUBMODULE=OFF \
            -DGHEX_USE_BUNDLED_LIBS=ON \
            -DGHEX_USE_BUNDLED_GRIDTOOLS=ON \
            -DBUILD_TESTING=OFF \
            -DGT_BUILD_TESTING=OFF \
            -DGT_INSTALL_EXAMPLES=OFF \
            -DGHEX_USE_BUNDLED_OOMPH=ON \
            -DGHEX_TRANSPORT_BACKEND=MPI \
            -DGHEX_USE_XPMEM=OFF \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DGHEX_BUILD_FORTRAN=OFF \
            -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
            -DGHEX_ENABLE_PARMETIS_BINDINGS=ON \
            -DMETIS_INCLUDE_DIR=/opt/metis/include \
            -DMETIS_LIB_DIR=/opt/metis/lib \
            -DPARMETIS_INCLUDE_DIR=/opt/parmetis/include \
            -DPARMETIS_LIB_DIR=/opt/parmetis/lib \
            -DMPIEXEC_PREFLAGS=--oversubscribe \
            -DGHEX_USE_GPU=OFF
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-cpu-ucx_clang:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-hip
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          CXX=/opt/rocm/llvm/bin/clang++ eckit_DIR=/opt/eckit Atlas_DIR=/opt/atlas cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGHEX_GIT_SUBMODULE=OFF \
            -DGHEX_USE_BUNDLED_LIBS=ON \
            -DGHEX_USE_BUNDLED_GRIDTOOLS=ON \
            -DBUILD_TESTING=OFF \
            -DGT_BUILD_TESTING=OFF \
            -DGT_INSTALL_EXAMPLES=OFF \
            -DGHEX_USE_BUNDLED_OOMPH=ON \
            -DGHEX_TRANSPORT_BACKEND=UCX \
            -DUCX_DIR=/opt/ucx \
            -DGHEX_USE_XPMEM=OFF \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DGHEX_BUILD_FORTRAN=OFF \
            -DGHEX_ENABLE_ATLAS_BINDINGS=ON \
            -DGHEX_ENABLE_PARMETIS_BINDINGS=ON \
            -DMETIS_INCLUDE_DIR=/opt/metis/include \
            -DMETIS_LIB_DIR=/opt/metis/lib \
            -DPARMETIS_INCLUDE_DIR=/opt/parmetis/include \
            -DPARMETIS_LIB_DIR=/opt/parmetis/lib \
            -DMPIEXEC_PREFLAGS=--oversubscribe \
            -DGHEX_USE_GPU=OFF
      - name: Build
        run: cmake --build build --parallel 2
      - name: Execute tests
        run: cd build && export SHLVL=1 && export OMPI_ALLOW_RUN_AS_ROOT=1 && export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 && export CTEST_OUTPUT_ON_FAILURE=1 && env && ctest

  build-gpu-amd:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-hip
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          CXX=/opt/rocm/llvm/bin/clang++ cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGHEX_GIT_SUBMODULE=OFF \
            -DGHEX_USE_BUNDLED_LIBS=ON \
            -DGHEX_USE_BUNDLED_GRIDTOOLS=ON \
            -DBUILD_TESTING=OFF \
            -DGT_BUILD_TESTING=OFF \
            -DGT_INSTALL_EXAMPLES=OFF \
            -DGHEX_USE_BUNDLED_OOMPH=ON \
            -DGHEX_TRANSPORT_BACKEND=UCX \
            -DUCX_DIR=/opt/ucx \
            -DGHEX_USE_XPMEM=OFF \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DGHEX_BUILD_FORTRAN=ON \
            -DGHEX_ENABLE_ATLAS_BINDINGS=OFF \
            -DGHEX_ENABLE_PARMETIS_BINDINGS=ON \
            -DMETIS_INCLUDE_DIR=/opt/metis/include \
            -DMETIS_LIB_DIR=/opt/metis/lib \
            -DPARMETIS_INCLUDE_DIR=/opt/parmetis/include \
            -DPARMETIS_LIB_DIR=/opt/parmetis/lib \
            -DMPIEXEC_PREFLAGS=--oversubscribe \
            -DGHEX_USE_GPU=ON \
            -DGHEX_GPU_TYPE=AMD
      - name: Build
        run: cmake --build build --parallel 2

  build-gpu-nvidia:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis-cuda-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure
        run: |
          echo "WORKFLOW"
          export SHLVL=1
          env
          ulimit -a
          ipcs -lm
          df
          cat /proc/cpuinfo
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Debug \
            -DGHEX_GIT_SUBMODULE=OFF \
            -DGHEX_USE_BUNDLED_LIBS=ON \
            -DGHEX_USE_BUNDLED_GRIDTOOLS=ON \
            -DBUILD_TESTING=OFF \
            -DGT_BUILD_TESTING=OFF \
            -DGT_INSTALL_EXAMPLES=OFF \
            -DGHEX_USE_BUNDLED_OOMPH=ON \
            -DGHEX_TRANSPORT_BACKEND=UCX \
            -DUCX_DIR=/opt/ucx \
            -DGHEX_USE_XPMEM=OFF \
            -DGHEX_WITH_TESTING=ON \
            -DGHEX_BUILD_BENCHMARKS=ON \
            -DGHEX_BUILD_FORTRAN=ON \
            -DGHEX_ENABLE_ATLAS_BINDINGS=OFF \
            -DGHEX_ENABLE_PARMETIS_BINDINGS=ON \
            -DMETIS_INCLUDE_DIR=/opt/metis/include \
            -DMETIS_LIB_DIR=/opt/metis/lib \
            -DPARMETIS_INCLUDE_DIR=/opt/parmetis/include \
            -DPARMETIS_LIB_DIR=/opt/parmetis/lib \
            -DMPIEXEC_PREFLAGS=--oversubscribe \
            -DGHEX_USE_GPU=ON \
            -DGHEX_GPU_TYPE=NVIDIA
      - name: Build
        run: cmake --build build --parallel 2

