name: Test pip

on:
  push:
    branches: [ master ]
    paths-ignore: 'doc/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 'doc/**'

jobs:
  testpip:
    name: "Pip build test + Python examples test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone w/ submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update pip and setup venv
        run: python -m pip install --upgrade pip && python -m venv ~/env && . ~/env/bin/activate && echo PATH=$PATH >> $GITHUB_ENV
      - name: Debug info Python
        run: |
          which python
          python --version
          pip --version
      - name: Build and install ghex using pip
        run: CMAKE_ARGS="-DMPIEXEC_PREFLAGS=--oversubscribe -DGHEX_USE_GPU=OFF" pip install ./bindings/python --user
      #- name: Check that build flags match
      #  run: |
      #    python -c "import arbor; print(arbor.config())" | grep -q "'arch': 'native'"
      #- name: Run Python tests
      #  run: python -m unittest discover -v -s python
      #- name: Run Python examples
      #  run: scripts/run_python_examples.sh
      #- name: Test executables
      #  run: scripts/test_executables.sh
