name: Test pip

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  testpip:
    name: "Pip build test + Python examples test"
    runs-on: ${{ matrix.os }}
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi-atlas-parmetis
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
    steps:
      - name: install python
        run: |
          apt update
          apt-get -y install python3-dev python3-venv python3-pybind11
      - name: Clone w/ submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update pip and setup venv
        run: python3 -m pip install --upgrade pip && python3 -m venv ~/env
             #&& . ~/env/bin/activate && echo PATH=$PATH >> $GITHUB_ENV
      - name: Debug info Python
        run: |
          which python3
          python3 --version
          pip3 --version
          echo $PATH
      - name: Install pytest etc
        run: . ~/env/bin/activate && python3 -m pip install -r ./bindings/python/requirements-test.txt
      - name: Build and install ghex using pip
        run: . ~/env/bin/activate && CMAKE_ARGS="-DMPIEXEC_PREFLAGS=--oversubscribe -DGHEX_USE_GPU=OFF" python3 -m pip install ./bindings/python
      - name: Run Python tests
        run: |
          export SHLVL=1
          export OMPI_ALLOW_RUN_AS_ROOT=1
          export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
          . ~/env/bin/activate
          python3 -m pytest -s ./test/bindings/python/
          mpirun --oversubscribe -np 4 python3 -m pytest -s --with-mpi ./test/bindings/python/
